Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -86,17 +86,13 @@ jobs:
         USE_CCACHE: 1
         CCACHE_DIR: /tmp/ccache
 
-    - name: List output directory contents
+    - name: List build directory contents
       run: |
-        echo "Listing contents of out/ directory"
-        ls -la out/ || echo "out directory not found"
-        echo "Listing contents of logs/ directory"
-        ls -la logs/ || echo "logs directory not found"
+        echo "Listing contents of build directory"
+        ls -la /home/runner/work/opengapps/opengapps/build/arm/19/ || echo "build directory not found"
 
     - name: Archive build artifacts
       uses: actions/upload-artifact@v4.5.0
       with:
         name: open-gapps-${{ env.ARCH }}-${{ env.API }}-${{ env.VARIANT }}
-        path: |
-          out/
-          logs/
+        path: /home/runner/work/opengapps/opengapps/build/arm/19/
